### ISSUE TITLE
[Feature request] Consider using DAE apply effect function when DAE is installed and active

### ISSUE THREAD

**Issue by mech-tools** [ElfFriend-DnD/foundryvtt-item-effects-to-chat-5e#1]
Hello,

A lot of foundry users use DAE/Times Up.

Using DAE apply effect function would also make use of the special DAE fields such as:
- Force display on token
- Stackable (especially this one)
- Special duration

The DAE function is: https://gitlab.com/tposney/dae/-/blob/master/src/module/dae.ts#L1331

![image](https://user-images.githubusercontent.com/1687854/149388397-d25899d4-a323-4ec6-9eb6-c846a0a72dcd.png)
![image](https://user-images.githubusercontent.com/1687854/149388533-9c18d265-bd38-4005-a074-0f8f8c2a1106.png)

**Comment by akrigline** [comment]
I believe all of the data from the origin effect is transferred to the target tokens, I wouldn't have expected the DAE data to rely on a specific application.

I'll take a look to double check that. I'm not terribly interested in doing any module detection to change application behavior but I might be convinced otherwise upon investigation

**Comment by mech-tools** [comment]
@akrigline Might be only for the Stackable option if not for the rest.
I tested that. With DAE application, it's ok, but not with this module.

**Comment by mech-tools** [comment]
@akrigline Sorry, didn't mean to close the issue -_-
