### ISSUE TITLE
Let players apply active effects when it targets self

### ISSUE THREAD

**Issue by kaelad02** [ElfFriend-DnD/foundryvtt-item-effects-to-chat-5e#4]
I was testing this out with the Barbarian's Rage feature. After using the feature the GM gets the chat card to apply the Rage active effect. I right-clicked on the chat message to reveal to everyone. The message showed up on the player's side but they couldn't drag the effect onto their token. It would make it easier on the GM if they could apply the effect themselves. If the item targets Self, could we show that chat message to the player too and let them drag the active effect onto themselves?

If this is done, the next step would be for spells that target allies, like Bless. Would be easier on the GM if the players could drag the Bless active effect onto their allies instead of requiring the GM to do it.

As an alternative, I suppose another way to make it easier on the GM is to set the targets differently if the feature targets self. Instead of setting the targets in the chat message to who the player had targeted, if the feature targets self it sets the targets of the effect to their token.

**Comment by akrigline** [comment]
This module's scope is purposefully limited, and what you're suggesting is _right_ on the edge of out of scope.

I've got a different module in the works which will automatically apply effects from items which only ever target "self."

There's an inherent permission hurdle to overcome with Foundry Core which makes it difficult to allow players to affect other creatures than they have ownership over. I'm not interested in putting socket bypasses into this module, as its purpose is to make it faster for the GM to do things in combat.

I can see the argument for having Player effects show up for player-casted abilities so that individual players can apply effects to actors they own. That's an interesting idea.

I'm hesitant to make the module more complex with settings for this behavior, so I'd want to come up with a rule-set that's intuitive for when a player-ability would appear in chat for players.

**Comment by kaelad02** [comment]
The "auto apply effects that target self" use case is what I'm most looking for. For me that feels like a "must have." The other use case of applying effects to allies, like Bless, is a "nice to have" but not necessary since I use Convenient Effects anyways. Kind of surprised to hear the former would be a separate module rather than included in this one, but glad to hear it's in the works.

**Comment by akrigline** [comment]
I've just tested this enough to be confident about initial release:

https://github.com/ElfFriend-DnD/foundryvtt-apply-self-effects-5e

Should be listed on the Foundry Listing as well. This is only for the behavior of "automatically applying an item's effects to the item's owner when it is rolled."

**Comment by kaelad02** [comment]
Thanks for the link.
